# Generated by Django 3.1.7 on 2021-05-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': {('Es_Alumno', 'Es Alumno'), ('Es_Docente', 'Es Docente')}},
        ),
    ]
