# Generated by Django 3.1.7 on 2021-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210531_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_alumno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_docente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_de_usuario',
        ),
    ]
