# Generated by Django 3.1.7 on 2021-05-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210519_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': {('Es_Alumno', 'Es Alumno'), ('Es_Docente', 'Es Docente')}},
        ),
    ]
