# Generated by Django 3.1.7 on 2021-05-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210519_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('is_teacher', 'Is Teacher'), ('is_student', 'Is Student'), ('is_admin', 'Is Admin'))},
        ),
    ]
